### ISSUE TITLE
No link on supermarket

### ISSUE THREAD

**Issue by spuder** [GoatOS/xml_file#2]
This looks like a great cookbook, however the supermarket is missing the link to github. 

https://supermarket.chef.io/cookbooks/xml_file

**Comment by spuder** [comment]
As a side note, the markdown rendering on the supermarket has all of the code blocks smashed together. They look correct on github.

**Comment by ranjib** [comment]
fixed. Thanks for pointing it out @spuder closing this. let me know if anything else is needed
