### ISSUE TITLE
Only one 'partial' is processed in an xml_file block when same xpath is used

### ISSUE THREAD

**Issue by dspartz** [GoatOS/xml_file#9]
xml_file '/opt/template.xml' do
  partial '//pipelines', template_file, before: '//pipeline'
  partial '//pipelines', 'second_partial.xml', before: '//pipeline'
end

only process the second one. This is because the code uses hash based on xpath

**Comment by ranjib** [comment]
closed via https://github.com/GoatOS/xml_file/pull/8
thanks @dspartz
